### Backtesting Stocks

In [57]:
import fix_yahoo_finance as yf
import pandas as pd
from pandas_datareader import data
import datetime
from bokeh.plotting import show,figure,output_file

In [66]:
start_day=datetime.datetime(2018,1,1)
end_day=datetime.datetime(2018,5,10)
yf.pdr_override() 
df=data.get_data_yahoo(tickers="AAPL", start=start_day, end=end_day)
df

[*********************100%***********************]  1 of 1 downloaded

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2018-01-02,170.160004,172.300003,169.259995,172.259995,170.901505,25555900
2018-01-03,172.529999,174.550003,171.960007,172.229996,170.871735,29517900
2018-01-04,172.539993,173.470001,172.080002,173.029999,171.665436,22434600
2018-01-05,173.440002,175.369995,173.050003,175.000000,173.619904,23660000
2018-01-08,174.350006,175.610001,173.929993,174.350006,172.975037,20567800
2018-01-09,174.550003,175.059998,173.410004,174.330002,172.955200,21584000
2018-01-10,173.160004,174.300003,173.000000,174.289993,172.915497,23959900
2018-01-11,174.589996,175.490005,174.490005,175.279999,173.897705,18667700
2018-01-12,176.179993,177.360001,175.649994,177.089996,175.693420,25418100
2018-01-16,177.899994,179.389999,176.139999,176.190002,174.800537,29565900
2018-01-17,176.149994,179.250000,175.070007,179.100006,177.687576,33888500
2018-01-18,179.369995,180.100006,178.250000,179.259995,177.846313,31193400
2018-01-19,178.610001,179.580002,177.410004,178.460007,177.052628,32425100
2018-01-22,177.300003,177.779999,176.600006,177.000000,175.604141,27108600
2018-01-23,177.300003,179.440002,176.820007,177.039993,175.643814,32689100
2018-01-24,177.250000,177.300003,173.199997,174.220001,172.846054,51105100
2018-01-25,174.509995,174.949997,170.529999,171.110001,169.760574,41529000
2018-01-26,172.000000,172.000000,170.059998,171.509995,170.157425,39143000
2018-01-29,170.160004,170.160004,167.070007,167.960007,166.635422,50640400
2018-01-30,165.529999,167.369995,164.699997,166.970001,165.653244,46048200
2018-01-31,166.869995,168.440002,166.500000,167.429993,166.109604,32478900
2018-02-01,167.169998,168.619995,166.759995,167.779999,166.456848,47230800
2018-02-02,166.000000,166.800003,160.100006,160.500000,159.234253,86593800
2018-02-05,159.100006,163.880005,156.000000,156.490005,155.255890,72738500
2018-02-06,154.830002,163.720001,154.000000,163.029999,161.744293,68243800
2018-02-07,163.089996,163.399994,159.070007,159.539993,158.281815,51608600
2018-02-08,160.289993,161.000000,155.029999,155.149994,153.926437,54390500
2018-02-09,157.070007,157.889999,150.240005,156.410004,155.809189,70672600
2018-02-12,158.500000,163.889999,157.509995,162.710007,162.084991,60819500
2018-02-13,161.949997,164.750000,161.649994,164.339996,163.708725,32549200
...,...,...,...,...,...,...
2018-03-29,167.809998,171.750000,166.899994,167.779999,167.135513,38398500
2018-04-02,166.639999,168.940002,164.470001,166.679993,166.039734,37586800
2018-04-03,167.639999,168.750000,164.880005,168.389999,167.743164,30278000
2018-04-04,164.880005,172.009995,164.770004,171.610001,170.950806,34605500
2018-04-05,172.580002,174.229996,172.080002,172.800003,172.136230,26933200
2018-04-06,170.970001,172.479996,168.199997,168.380005,167.733215,35005300
2018-04-09,169.880005,173.089996,169.850006,170.050003,169.396790,29017700
2018-04-10,173.000000,174.000000,171.529999,173.250000,172.584503,28408600
2018-04-11,172.229996,173.919998,171.699997,172.440002,171.777618,22431600
2018-04-12,173.410004,175.000000,173.039993,174.139999,173.471085,22889300
2018-04-13,174.779999,175.839996,173.850006,174.729996,174.058807,25124300
2018-04-16,175.029999,176.190002,174.830002,175.820007,175.144638,21578400
2018-04-17,176.490005,178.940002,176.410004,178.240005,177.555328,26605400
2018-04-18,177.809998,178.820007,176.880005,177.839996,177.156860,20754500
2018-04-19,173.759995,175.389999,172.660004,172.800003,172.136230,34808800
2018-04-20,170.600006,171.220001,165.429993,165.720001,165.083420,65491100
2018-04-23,166.830002,166.919998,164.089996,165.240005,164.605270,36515500
2018-04-24,165.669998,166.330002,161.220001,162.940002,162.314102,33692000
2018-04-25,162.619995,165.419998,162.410004,163.649994,163.021362,28382100
2018-04-26,164.119995,165.729996,163.369995,164.220001,163.589188,27963000
2018-04-27,164.000000,164.330002,160.630005,162.320007,161.696487,35655800
2018-04-30,162.130005,167.259995,161.839996,165.259995,164.625183,42427400
2018-05-01,166.410004,169.199997,165.270004,169.100006,168.450439,53569400
2018-05-02,175.229996,177.750000,173.800003,176.570007,175.891754,66539400
2018-05-03,175.880005,177.500000,174.440002,176.889999,176.210510,34068200
2018-05-04,178.250000,184.250000,178.169998,183.830002,183.123856,56201300
2018-05-07,185.179993,187.669998,184.750000,185.160004,184.448746,42451400
2018-05-08,184.990005,186.220001,183.669998,186.050003,185.335327,28402800
2018-05-09,186.550003,187.399994,185.220001,187.360001,186.640305,23211200
2018-05-10,187.740005,190.369995,187.649994,190.039993,189.309998,27989300

In [68]:
writer = pd.ExcelWriter('output.xlsx')
df.to_excel(writer,'Sheet1')
writer.save()

In [69]:
df['SMA']=0.00
k=3
for i in range(0, len(df)-4):
    k=k+1
    for j in range(i,i+5):
        df['SMA'][k]=df['Adj Close'][j]+df['SMA'][k]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [70]:
df['SMA']=df['SMA']/5
df

,Open,High,Low,Close,Adj Close,Volume,SMA
Date,,,,,,,
2018-01-02,170.160004,172.300003,169.259995,172.259995,170.901505,25555900,0.000000
2018-01-03,172.529999,174.550003,171.960007,172.229996,170.871735,29517900,0.000000
2018-01-04,172.539993,173.470001,172.080002,173.029999,171.665436,22434600,0.000000
2018-01-05,173.440002,175.369995,173.050003,175.000000,173.619904,23660000,0.000000
2018-01-08,174.350006,175.610001,173.929993,174.350006,172.975037,20567800,172.006723
2018-01-09,174.550003,175.059998,173.410004,174.330002,172.955200,21584000,172.417462
2018-01-10,173.160004,174.300003,173.000000,174.289993,172.915497,23959900,172.826215
2018-01-11,174.589996,175.490005,174.490005,175.279999,173.897705,18667700,173.272669
2018-01-12,176.179993,177.360001,175.649994,177.089996,175.693420,25418100,173.687372
2018-01-16,177.899994,179.389999,176.139999,176.190002,174.800537,29565900,174.052472
2018-01-17,176.149994,179.250000,175.070007,179.100006,177.687576,33888500,174.998947
2018-01-18,179.369995,180.100006,178.250000,179.259995,177.846313,31193400,175.985110
2018-01-19,178.610001,179.580002,177.410004,178.460007,177.052628,32425100,176.616095
2018-01-22,177.300003,177.779999,176.600006,177.000000,175.604141,27108600,176.598239
2018-01-23,177.300003,179.440002,176.820007,177.039993,175.643814,32689100,176.766894
2018-01-24,177.250000,177.300003,173.199997,174.220001,172.846054,51105100,175.798590
2018-01-25,174.509995,174.949997,170.529999,171.110001,169.760574,41529000,174.181442
2018-01-26,172.000000,172.000000,170.059998,171.509995,170.157425,39143000,172.802402
2018-01-29,170.160004,170.160004,167.070007,167.960007,166.635422,50640400,171.008658
2018-01-30,165.529999,167.369995,164.699997,166.970001,165.653244,46048200,169.010544
2018-01-31,166.869995,168.440002,166.500000,167.429993,166.109604,32478900,167.663254
2018-02-01,167.169998,168.619995,166.759995,167.779999,166.456848,47230800,167.002509
2018-02-02,166.000000,166.800003,160.100006,160.500000,159.234253,86593800,164.817874
2018-02-05,159.100006,163.880005,156.000000,156.490005,155.255890,72738500,162.541968
2018-02-06,154.830002,163.720001,154.000000,163.029999,161.744293,68243800,161.760178
2018-02-07,163.089996,163.399994,159.070007,159.539993,158.281815,51608600,160.194620
2018-02-08,160.289993,161.000000,155.029999,155.149994,153.926437,54390500,157.688538
2018-02-09,157.070007,157.889999,150.240005,156.410004,155.809189,70672600,157.003525
2018-02-12,158.500000,163.889999,157.509995,162.710007,162.084991,60819500,158.369345
2018-02-13,161.949997,164.750000,161.649994,164.339996,163.708725,32549200,158.762231
...,...,...,...,...,...,...,...
2018-03-29,167.809998,171.750000,166.899994,167.779999,167.135513,38398500,167.416431
2018-04-02,166.639999,168.940002,164.470001,166.679993,166.039734,37586800,167.763092
2018-04-03,167.639999,168.750000,164.880005,168.389999,167.743164,30278000,166.890454
2018-04-04,164.880005,172.009995,164.770004,171.610001,170.950806,34605500,167.541943
2018-04-05,172.580002,174.229996,172.080002,172.800003,172.136230,26933200,168.801089
2018-04-06,170.970001,172.479996,168.199997,168.380005,167.733215,35005300,168.920630
2018-04-09,169.880005,173.089996,169.850006,170.050003,169.396790,29017700,169.592041
2018-04-10,173.000000,174.000000,171.529999,173.250000,172.584503,28408600,170.560309
2018-04-11,172.229996,173.919998,171.699997,172.440002,171.777618,22431600,170.725671
2018-04-12,173.410004,175.000000,173.039993,174.139999,173.471085,22889300,170.992642
2018-04-13,174.779999,175.839996,173.850006,174.729996,174.058807,25124300,172.257761
2018-04-16,175.029999,176.190002,174.830002,175.820007,175.144638,21578400,173.407330
2018-04-17,176.490005,178.940002,176.410004,178.240005,177.555328,26605400,174.401495
2018-04-18,177.809998,178.820007,176.880005,177.839996,177.156860,20754500,175.477344
2018-04-19,173.759995,175.389999,172.660004,172.800003,172.136230,34808800,175.210373
2018-04-20,170.600006,171.220001,165.429993,165.720001,165.083420,65491100,173.415295
2018-04-23,166.830002,166.919998,164.089996,165.240005,164.605270,36515500,171.307422
2018-04-24,165.669998,166.330002,161.220001,162.940002,162.314102,33692000,168.259176
2018-04-25,162.619995,165.419998,162.410004,163.649994,163.021362,28382100,165.432077
2018-04-26,164.119995,165.729996,163.369995,164.220001,163.589188,27963000,163.722668
2018-04-27,164.000000,164.330002,160.630005,162.320007,161.696487,35655800,163.045282
2018-04-30,162.130005,167.259995,161.839996,165.259995,164.625183,42427400,163.049264
2018-05-01,166.410004,169.199997,165.270004,169.100006,168.450439,53569400,164.276532
2018-05-02,175.229996,177.750000,173.800003,176.570007,175.891754,66539400,166.850610
2018-05-03,175.880005,177.500000,174.440002,176.889999,176.210510,34068200,169.374875
2018-05-04,178.250000,184.250000,178.169998,183.830002,183.123856,56201300,173.660348
2018-05-07,185.179993,187.669998,184.750000,185.160004,184.448746,42451400,177.625061
2018-05-08,184.990005,186.220001,183.669998,186.050003,185.335327,28402800,181.002039
2018-05-09,186.550003,187.399994,185.220001,187.360001,186.640305,23211200,183.151749
2018-05-10,187.740005,190.369995,187.649994,190.039993,189.309998,27989300,185.771646

In [72]:
df['SMA (25)']=0.00
k=23
for i in range(0, len(df)-24):
    k=k+1
    for j in range(i,i+25):
        df['SMA (25)'][k]=df['Adj Close'][j]+df['SMA (25)'][k]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [73]:
df['SMA (25)']=df['SMA (25)']/25
df

,Open,High,Low,Close,Adj Close,Volume,SMA,SMA (25)
Date,,,,,,,,
2018-01-02,170.160004,172.300003,169.259995,172.259995,170.901505,25555900,0.000000,0.000000
2018-01-03,172.529999,174.550003,171.960007,172.229996,170.871735,29517900,0.000000,0.000000
2018-01-04,172.539993,173.470001,172.080002,173.029999,171.665436,22434600,0.000000,0.000000
2018-01-05,173.440002,175.369995,173.050003,175.000000,173.619904,23660000,0.000000,0.000000
2018-01-08,174.350006,175.610001,173.929993,174.350006,172.975037,20567800,172.006723,0.000000
2018-01-09,174.550003,175.059998,173.410004,174.330002,172.955200,21584000,172.417462,0.000000
2018-01-10,173.160004,174.300003,173.000000,174.289993,172.915497,23959900,172.826215,0.000000
2018-01-11,174.589996,175.490005,174.490005,175.279999,173.897705,18667700,173.272669,0.000000
2018-01-12,176.179993,177.360001,175.649994,177.089996,175.693420,25418100,173.687372,0.000000
2018-01-16,177.899994,179.389999,176.139999,176.190002,174.800537,29565900,174.052472,0.000000
2018-01-17,176.149994,179.250000,175.070007,179.100006,177.687576,33888500,174.998947,0.000000
2018-01-18,179.369995,180.100006,178.250000,179.259995,177.846313,31193400,175.985110,0.000000
2018-01-19,178.610001,179.580002,177.410004,178.460007,177.052628,32425100,176.616095,0.000000
2018-01-22,177.300003,177.779999,176.600006,177.000000,175.604141,27108600,176.598239,0.000000
2018-01-23,177.300003,179.440002,176.820007,177.039993,175.643814,32689100,176.766894,0.000000
2018-01-24,177.250000,177.300003,173.199997,174.220001,172.846054,51105100,175.798590,0.000000
2018-01-25,174.509995,174.949997,170.529999,171.110001,169.760574,41529000,174.181442,0.000000
2018-01-26,172.000000,172.000000,170.059998,171.509995,170.157425,39143000,172.802402,0.000000
2018-01-29,170.160004,170.160004,167.070007,167.960007,166.635422,50640400,171.008658,0.000000
2018-01-30,165.529999,167.369995,164.699997,166.970001,165.653244,46048200,169.010544,0.000000
2018-01-31,166.869995,168.440002,166.500000,167.429993,166.109604,32478900,167.663254,0.000000
2018-02-01,167.169998,168.619995,166.759995,167.779999,166.456848,47230800,167.002509,0.000000
2018-02-02,166.000000,166.800003,160.100006,160.500000,159.234253,86593800,164.817874,0.000000
2018-02-05,159.100006,163.880005,156.000000,156.490005,155.255890,72738500,162.541968,0.000000
2018-02-06,154.830002,163.720001,154.000000,163.029999,161.744293,68243800,161.760178,170.719362
2018-02-07,163.089996,163.399994,159.070007,159.539993,158.281815,51608600,4428.178675,170.214575
2018-02-08,160.289993,161.000000,155.029999,155.149994,153.926437,54390500,4413.052903,169.536763
2018-02-09,157.070007,157.889999,150.240005,156.410004,155.809189,70672600,4395.422592,168.902513
2018-02-12,158.500000,163.889999,157.509995,162.710007,162.084991,60819500,4380.932165,168.441116
2018-02-13,161.949997,164.750000,161.649994,164.339996,163.708725,32549200,4369.790138,168.070464
...,...,...,...,...,...,...,...,...
2018-03-29,167.809998,171.750000,166.899994,167.779999,167.135513,38398500,4530.711216,174.343717
2018-04-02,166.639999,168.940002,164.470001,166.679993,166.039734,37586800,4526.356018,173.992272
2018-04-03,167.639999,168.750000,164.880005,168.389999,167.743164,30278000,4516.697263,173.570698
2018-04-04,164.880005,172.009995,164.770004,171.610001,170.950806,34605500,4506.809384,173.300540
2018-04-05,172.580002,174.229996,172.080002,172.800003,172.136230,26933200,4501.314578,173.088557
2018-04-06,170.970001,172.479996,168.199997,168.380005,167.733215,35005300,4496.134558,172.824775
2018-04-09,169.880005,173.089996,169.850006,170.050003,169.396790,29017700,4490.211410,172.579321
2018-04-10,173.000000,174.000000,171.529999,173.250000,172.584503,28408600,4485.043326,172.437069
2018-04-11,172.229996,173.919998,171.699997,172.440002,171.777618,22431600,4481.652398,172.268519
2018-04-12,173.410004,175.000000,173.039993,174.139999,173.471085,22889300,4477.705623,172.233056
2018-04-13,174.779999,175.839996,173.850006,174.729996,174.058807,25124300,4478.084161,172.144995
2018-04-16,175.029999,176.190002,174.830002,175.820007,175.144638,21578400,4477.032207,171.979235
2018-04-17,176.490005,178.940002,176.410004,178.240005,177.555328,26605400,4473.882375,171.840570
2018-04-18,177.809998,178.820007,176.880005,177.839996,177.156860,20754500,4471.491595,171.755697
2018-04-19,173.759995,175.389999,172.660004,172.800003,172.136230,34808800,4469.102797,171.530964
2018-04-20,170.600006,171.220001,165.429993,165.720001,165.083420,65491100,4461.689387,171.015751
2018-04-23,166.830002,166.919998,164.089996,165.240005,164.605270,36515500,4446.701189,170.506514
2018-04-24,165.669998,166.330002,161.220001,162.940002,162.314102,33692000,4430.922031,170.014013
2018-04-25,162.619995,165.419998,162.410004,163.649994,163.021362,28382100,4415.782401,169.552193
2018-04-26,164.119995,165.729996,163.369995,164.220001,163.589188,27963000,4402.527490,169.271276
2018-04-27,164.000000,164.330002,160.630005,162.320007,161.696487,35655800,4394.827186,169.011080
2018-04-30,162.130005,167.259995,161.839996,165.259995,164.625183,42427400,4388.326254,169.023830
2018-05-01,166.410004,169.199997,165.270004,169.100006,168.450439,53569400,4389.872278,168.877593
2018-05-02,175.229996,177.750000,173.800003,176.570007,175.891754,66539400,4388.790441,169.205529
2018-05-03,175.880005,177.500000,174.440002,176.889999,176.210510,34068200,4399.513101,169.620329
2018-05-04,178.250000,184.250000,178.169998,183.830002,183.123856,56201300,4414.168584,170.259863
2018-05-07,185.179993,187.669998,184.750000,185.160004,184.448746,42451400,4434.121640,170.996224
2018-05-08,184.990005,186.220001,183.669998,186.050003,185.335327,28402800,4455.907630,171.699910
2018-05-09,186.550003,187.399994,185.220001,187.360001,186.640305,23211200,4475.649503,172.327490
2018-05-10,187.740005,190.369995,187.649994,190.039993,189.309998,27989300,4493.958899,173.014441